name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Ruby environment
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # Use latest stable Ruby

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # 4. Build the Jekyll site
      - name: Build site
        run: |
          bundle exec jekyll build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
